[main]
# Force TLS for security
ciphers = ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256
minVersion = TLSv1.2
requestCert = false
rejectUnauthorized = false
key = tls/anon.li.pem
cert = tls/anon.li.pem